name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - azure-core=1.30.2
  - azure-data-tables=12.4.4
  - azure-functions=1.13.0
  - azure-cosmos=4.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.8
  - isodate=0.6.1
  - libffi=3.4.4
  - lz4-c=1.9.4
  - multidict=6.0.5
  - openssl=3.3.1
  - pip=24.2
  - pip:
      - azure-functions
      - azure-cosmos
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yarl=1.9.4
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
